# docker-compose-production.yml
version: "3"
services:
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./data:/var/lib/mysql
  app-flask:
    build: ./app
    links:
      - db
    ports:
      - "5000:5000"
    depends_on:
      - lista-de-compras-letsencrypt

  lista-de-compras-letsencrypt:
    image: linuxserver/letsencrypt
    container_name: lista-de-compras-letsencrypt
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./config/letsencrypt:/config
    environment:
      - EMAIL=mikelet@gmail.com
      - URL=lista-de-compras.ml
      - SUBDOMAINS=www,api
      - VALIDATION=http
      - TZ=America/Sao_Paulo
      - PUID=0
      - PGID=0